data_attributes_list = ['url', 'date', 'content', 'renderedContent', 'id',
                               'user.username', 'user.id', 'user.displayname', 'user.description',
                               'user.rawDescription', 'user.descriptionUrls', 'user.verified', 'user.created',
                               'user.followersCount', 'user.friendsCount', 'user.statusesCount',
                               'user.favouritesCount', 'user.listedCount', 'user.mediaCount', 'user.location',
                               'user.protected', 'user.linkUrl', 'user.linkTcourl', 'user.profileImageUrl',
                               'user.profileBannerUrl', 'user.label', 'user', 'replyCount', 'retweetCount',
                               'likeCount', 'quoteCount', 'conversationId', 'lang', 'source', 'sourceUrl',
                               'sourceLabel', 'outlinks', 'tcooutlinks', 'media', 'retweetedTweet',
                               'quotedTweet', 'mentionedUsers', 'coordinates', 'place', 'hashtags', 'cashtags']